### ISSUE TITLE
Gem dependency prevents proper installation

### ISSUE THREAD

**Issue by styliii** [cwjohnston/chef-hipchat#2]
Trying to use this on opswork, and I'm probably missing something.

I literally copied the repo (ex .gitignore) into my cookbooks under dir "hipchat".  In my deploy/recipes/default.rb add

```
include_recipe 'hipchat'
  hipchat_msg 'bad news' do
      room 'web'
      token 'my_token'
      nickname 'opswork'
      message "Problem with deployment: #{some_error}.  Check it out."
      color 'red'
    end
end
```

Then in deploy/metadata.rb, I added line:

```
depends "hipchat"
```

Am I supposed to reference where the gems need to be installed from?  Is there an equivalent gemfile I need to fix?

```
[2013-08-16T23:33:35+00:00] DEBUG: Gem::InstallError: ruby_block[Compile Custom OpsWorks Run List] (opsworks_custom_cookbooks::execute line 3) had an error: Gem::InstallError: chef_gem[hipchat] (hipchat::default line 1) had an error: Gem::InstallError: httparty requires multi_xml (>= 0.5.2)
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:232:in `ensure_dependency'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:408:in `ensure_dependencies_met'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:407:in `each'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:407:in `ensure_dependencies_met'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:158:in `install'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:297:in `install'
/usr/lib/ruby/1.8/fileutils.rb:243:in `each_with_index'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:270:in `each'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:270:in `each_with_index'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:270:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:169:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:192:in `with_correct_verbosity'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:168:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:103:in `with_gem_sources'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:167:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:476:in `install_package'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package.rb:82:in `action_install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:151:in `converge_by'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package.rb:80:in `action_install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `send'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/site-cookbooks/hipchat/recipes/default.rb:11:in `from_file'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_version.rb:346:in `load_recipe'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:151:in `load_recipe'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:132:in `include_recipe'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:131:in `each'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:131:in `include_recipe'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/opt/aws/opsworks/releases/20130806085854_205/site-cookbooks/deploy/recipes/default.rb:2:in `from_file'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_version.rb:346:in `load_recipe'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:151:in `load_recipe'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:139:in `compile_recipes'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:137:in `each'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:86:in `load'
/opt/aws/opsworks/releases/20130806085854_205/site-cookbooks/opsworks_custom_cookbooks/recipes/execute.rb:15:in `from_file'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/ruby_block.rb:33:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/ruby_block.rb:33:in `action_run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:151:in `converge_by'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/ruby_block.rb:32:in `action_run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `send'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:50:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `each'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:81:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:404:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:469:in `do_run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in `run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in `run_application'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `run_application'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16
[2013-08-16T23:33:35+00:00] FATAL: Gem::InstallError: ruby_block[Compile Custom OpsWorks Run List] (opsworks_custom_cookbooks::execute line 3) had an error: Gem::InstallError: chef_gem[hipchat] (hipchat::default line 1) had an error: Gem::InstallError: httparty requires multi_xml (>= 0.5.2)
```

**Comment by styliii** [comment]
I've also tried individually adding each gem.

In hipchat/recipes/default.rb

```
hipchat = chef_gem 'hipchat' do
  action :nothing
end

httparty = chef_gem 'httparty' do
  action :nothing
end

multi_xml = chef_gem 'multi_xml' do
  action :nothing
end

multi_xml.run_action(:install)

httparty.run_action(:install)

hipchat.run_action(:install)
```

This is the stack trace that I get running that.... I added some blank lines to help with readability

```
[2013-08-16T23:58:50+00:00] INFO: Processing chef_gem[hipchat] action nothing (hipchat::default line 1)
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[hipchat] using gem from running ruby environment
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[hipchat] no installed version found for hipchat (>= 0)
[2013-08-16T23:58:50+00:00] DEBUG: Doing nothing for chef_gem[hipchat]

[2013-08-16T23:58:50+00:00] INFO: Processing chef_gem[httparty] action nothing (hipchat::default line 5)
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[httparty] using gem from running ruby environment
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[httparty] no installed version found for httparty (>= 0)
[2013-08-16T23:58:50+00:00] DEBUG: Doing nothing for chef_gem[httparty]

[2013-08-16T23:58:50+00:00] INFO: Processing chef_gem[multi_xml] action nothing (hipchat::default line 9)
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[multi_xml] using gem from running ruby environment
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[multi_xml] no installed version found for multi_xml (>= 0)
[2013-08-16T23:58:50+00:00] DEBUG: Doing nothing for chef_gem[multi_xml]

[2013-08-16T23:58:50+00:00] INFO: Processing chef_gem[multi_xml] action install (hipchat::default line 9)
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[multi_xml] using gem from running ruby environment
[2013-08-16T23:58:50+00:00] DEBUG: chef_gem[multi_xml] no installed version found for multi_xml (>= 0)
[2013-08-16T23:58:53+00:00] DEBUG:  found gem multi_xml version 0.5.5 for platform ruby from http://rubygems.org/

[2013-08-16T23:58:58+00:00] INFO: Processing chef_gem[httparty] action install (hipchat::default line 5)
[2013-08-16T23:58:58+00:00] DEBUG: chef_gem[httparty] using gem from running ruby environment
[2013-08-16T23:58:58+00:00] DEBUG: chef_gem[httparty] no installed version found for httparty (>= 0)
[2013-08-16T23:58:58+00:00] DEBUG:  found gem httparty version 0.11.0 for platform ruby from http://rubygems.org/
[2013-08-16T23:59:02+00:00] DEBUG: filtered backtrace of compile error: 
[2013-08-16T23:59:02+00:00] DEBUG: filtered backtrace of compile error: 
[2013-08-16T23:59:02+00:00] DEBUG: backtrace entry for compile error: '/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:232:in `ensure_dependency''
[2013-08-16T23:59:02+00:00] DEBUG: Line number of compile error: '232'
[2013-08-16T23:59:02+00:00] ERROR: Caught exception while compiling opsworks custom run list: Gem::InstallError 
- chef_gem[httparty] (hipchat::default line 5) had an error: Gem::InstallError: httparty requires multi_xml (>= 0.5.2) - /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:232:in `ensure_dependency'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:408:in `ensure_dependencies_met'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:407:in `each'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:407:in `ensure_dependencies_met'
/usr/lib/ruby/vendor_ruby/rubygems/installer.rb:158:in `install'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:297:in `install'
/usr/lib/ruby/1.8/fileutils.rb:243:in `each_with_index'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:270:in `each'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:270:in `each_with_index'
/usr/lib/ruby/vendor_ruby/rubygems/dependency_installer.rb:270:in `install'

```

Looks like a problem with "httparty"?

**Comment by michaelglass** [comment]
are you running this in why-run mode?

**Comment by cwjohnston** [comment]
It's my understanding that OpsWorks runs Chef inside a bundler environment, so special tricks are required to properly install gems into that context so Chef can see them. I am not in a position to work on this myself, but I would be happy to entertain a pull request for it.
